language: node_js

node_js:
  - '8.9.4'

before_install:
  - sudo apt-get install mocha

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test #caso vocÃª tenha algum teste para ser rodado
  - bash ./teste.sh
  - bash ./deploy.sh